from snakemake.utils import min_version

min_version("6.10.0")

# Configuration file containing all user-specified settings
configfile: "config/config.yml"

report: "report/workflow.rst"


include: "rules/qiime2_viz.smk"
include: "rules/rmd_report.smk"


rule all:
	input:
		"index.html",

		# "data/features.csv",
        # "data/metadata.csv",
        # "data/taxonomy.csv",
        # "data/shannon.csv",

        # "resources/feature_table.qza",
        # "resources/sample_metadata.tsv",
        # "resources/taxonomy.qza",
        # "resources/rooted_tree.qza",
        # "resources/shannon_vector.qza",

		"data/q2_ps.rds",

		"figures/venndiagram.svg",
		"figures/lineplot.svg",
		"figures/jitterplot.svg",
		"figures/pcoa.svg",
		"figures/heatmap.svg",


