from snakemake.utils import min_version

min_version("6.10.0")

# Configuration file containing all user-specified settings
configfile: "config/config.yml"

report: "report/workflow.rst"


include: "rules/visual_types.smk"
# include: "rules/.smk"
# include: "rules/.smk"
# include: "rules/.smk"
# include: "rules/.smk"
include: "rules/rmd_report.smk"

report: "report/workflow.rst"


rule all:
    input: 
    	"index.html",    
        # "visual_types/explore_n_visualize.Rmd",
        expand("visual_types/clusters/{prefix}.Rmd", prefix=config["clusters"]),
        expand("visual_types/heatmaps/{prefix}.Rmd", prefix=config["heatmaps"]),
        expand("visual_types/barplots/{prefix}.Rmd", prefix=config["barplots"]),
        expand("visual_types/boxplots/{prefix}.Rmd", prefix=config["boxplots"]),
        expand("visual_types/ordinations/{prefix}.Rmd", prefix=config["ordinations"]),
        expand("visual_types/phylotrees/{prefix}.Rmd", prefix=config["phylotrees"]),
