from snakemake.utils import min_version

min_version("6.10.0")

# Configuration file containing all user-specified settings
configfile: "config/config.yml"

report: "report/workflow.rst"


include: "rules/import_demo_data.smk"
include: "rules/rmd_report.smk"

report: "report/workflow.rst"


rule all:
    input: 
        "figures/q2r_lineplot.svg",
        "figures/q2r_jitterplot.svg",
        "figures/q2r_pcoa.svg",
        "figures/q2r_heatmap.svg",
        "figures/q2r_barplot.svg",

        # "data/processed_objects.rda",
        # "data/feature_table.qza",
        # "data/sample_metadata.tsv",
        # "data/taxonomy.qza",
        # "data/rooted_tree.qza",
        # "data/shannon_vector.qza",

        # "data/features.csv",
        # "data/metadata.csv",
        # "data/taxonomy.csv",
        # "data/shannon.csv",

        "report.html",
        # "images/smkreport/screenshot.png",
        # "results/project_tree.txt",
        # "dags/rulegraph.svg",
        # "dags/rulegraph.png",

        "index.html",